package:
  name: nsis_conda
  version: 0.1.1

source:
  git_url: ..

build:
  string: nsis_0

requirements:
  build:
    - execdos
  run:
    - execdos

about:
  home: https://github.com/faph/NSIS-Conda-Macros
  license: MIT
  license_file: LICENSE
  summary: Install conda applications using NSIS.
  readme: README.md
