package:
  name: conda_macros
  version: 0.1.3

source:
  git_url: ..

build:
  string: nsis_0

requirements:
  build: []
  run:
  - nsis
  - execdos

about:
  home: https://github.com/faph/NSIS-Conda-Macros
  license: MIT
  license_file: LICENSE
  summary: Install conda applications using NSIS.
  readme: README.md
